# Generated by Django 6.0.6 on 2026-06-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-bag', max_length=60)),
                ('button_label', models.CharField(max_length=80)),
                ('button_variant', models.CharField(choices=[('primary', 'Primary'), ('outline', 'Outline')], default='primary', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mode de commande',
                'verbose_name_plural': 'Modes de commande',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='QR Food Djibouti', max_length=120)),
                ('hero_badge', models.CharField(default='Scan & Commande', max_length=120)),
                ('hero_title', models.CharField(default='Commandez en un scan,', max_length=200)),
                ('hero_subtitle', models.CharField(default='savourez sans attendre', max_length=200)),
                ('hero_text', models.TextField(default='Sur place ou à emporter — commandez depuis votre téléphone, sans application à installer.')),
                ('modes_title', models.CharField(default='Comment souhaitez-vous commander ?', max_length=200)),
                ('modes_subtitle', models.CharField(default='Choisissez une option — pas de livraison à domicile', max_length=200)),
                ('cta_title', models.CharField(default='Prêt à commander ?', max_length=200)),
                ('cta_text', models.CharField(default='Découvrez burgers, pizzas, boissons et desserts.', max_length=200)),
                ('location', models.CharField(default='Djibouti-ville', max_length=200)),
                ('hours', models.CharField(default='11h – 23h', max_length=120)),
                ('is_open', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-star', max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Atout accueil',
                'verbose_name_plural': 'Atouts accueil',
                'ordering': ['order', 'id'],
            },
        ),
    ]
