# Generated by Django 6.0.6 on 2026-06-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(default='bi-grid', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie menu',
                'verbose_name_plural': 'Catégories menu',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='MenuProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(help_text='Prix en FDJ')),
                ('image', models.URLField(max_length=500)),
                ('available', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.menucategory')),
            ],
            options={
                'verbose_name': 'Produit menu',
                'verbose_name_plural': 'Produits menu',
                'ordering': ['order', 'id'],
            },
        ),
    ]
